### ISSUE TITLE
Class Diagram

### ISSUE THREAD

**Issue by anhtuduong** [RadiantIQ/RadiantIQ#10]
[class-diagram](https://drive.google.com/file/d/1pVBIFn8zJEXLvCWnm6gus1W7aMDOuW9x/view?usp=sharing)
[class-diagram-instructions](https://didatticaonline.unitn.it/dol/pluginfile.php/1822269/mod_resource/content/2/L11-ClassDiagram.pdf)

**Comment by LorenzoCattai** [comment]
Completed for D1.
