### ISSUE TITLE
Wrong Commit Standard

### ISSUE THREAD

**Issue by LorenzoCattai** [RadiantIQ/RadiantIQ#12]
As initially decided together only [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) should be used as commit messages, this is not the case.

**Comment by LorenzoCattai** [comment]
I am currently rewriting the repository history as luckly we just have very few commits, I am also committing the initial documents that we produced together under @RadiantIQ while the makefile and anything new under their respective creator.

**Comment by anhtuduong** [comment]
@LorenzoCattai I just pull the git in my computer and it seems impossible:

![Image](https://github.com/RadiantIQ/RadiantIQ/assets/76017474/290f196e-1f14-40c2-b686-1afbf77d8cce)

One of my experience is not changing the things that already made. But only this time it is OK, as we just decided together to change the branch things.

**Comment by LorenzoCattai** [comment]
I know, this is absolutely not something that should ever be done, but in this context it was only fair as we all agreed together on using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0) and we also decided to change the branch naming scheme.
I think the easiest thing you can do is to export your commits as `.patch` files and apply them later when I finish remaking all the branches and commits.
I will also add a comment on #1 regarding the now inexisting PR commit hash.

**Comment by LorenzoCattai** [comment]
Found the time to finally finish this.
