### ISSUE TITLE
Questionable Branch Naming Scheme

### ISSUE THREAD

**Issue by LorenzoCattai** [RadiantIQ/RadiantIQ#13]
The current naming scheme uses numbers in the beginning of branch names, for example `6-functional-requirements`, I propose switching to a more standard branch naming style that uses the branch function instead, for example `feature/functional-requirements`, [this](https://medium.com/@abhay.pixolo/naming-conventions-for-git-branches-a-cheatsheet-8549feca2534) is more or less the standard I see used most of the times on git repositories.

**Comment by anhtuduong** [comment]
I agree, and in addition: I agree on adding the "type" of branch (like feature/... doc/...). But still keeping the number after that, the number indicates the current number of branch or issue we have dealed with and acts as a serial (or ticket) number, we will need serial number later in the development. So at the end a branch name can be: docs/1-formalize-documentation-for-D1.

If we agree, i will follow this convention after the D1, i would not recommend changing the existed branchs

**Comment by LorenzoCattai** [comment]
That would be perfect, we could use something like `ISSUE/TYPE/NAME` or `TYPE/NAME` if it's not worth a dedicated issue maybe.
For example `6/docs/functional-requirments`.

**Comment by anhtuduong** [comment]
When creating a branch from an issue, for example:
Issue name: `Functional requirement`
-> the default branch name that github generates: `6-functional-requirement`
It would be easy if we just add the prefix type `docs/`
The ticket number can be easily track and search just by typing the number, not necessary to put the number in the head. And `docs/6-functional-requirement` makes more sense in semantic speaking...
@LorenzoCattai @pertipo What do you think?

**Comment by LorenzoCattai** [comment]
I think your naming scheme makes more sense and is more aligned with the standard I linked even, I 100% agree.

**Comment by pertipo** [comment]
I agree, adding the number after the type prefix is clear and functional

**Comment by LorenzoCattai** [comment]
Also, I think it would be nice to consider the `D1` (`Deliverable 1`) the first development release `0.1.0` even tho there is no code yet it would make quite a lot logical sense, we could even call `Formalize documentation for D1` just `D1 (Deliverable 1)` so that we can have a branch named `release/1-D1` which feels also way more like a proper `release`.
@anhtuduong @pertipo

**Comment by anhtuduong** [comment]
I agree! Please create that branch. D1 will end when that branch merge into `main`. @LorenzoCattai Can you take care of this? Thanks!!!

**Comment by LorenzoCattai** [comment]
Working on it.

**Comment by LorenzoCattai** [comment]
I created all the branches tho used "_" as separators like it's on the files now, for the release branch I am doing as suggested in #14 for now, leave feedback here on the topic if there are problems with it.

**Comment by LorenzoCattai** [comment]
> I created all the branches tho used "_" as separators like it's on the files now, for the release branch I am doing as suggested in [#14](https://github.com/RadiantIQ/RadiantIQ/issues/14) for now, leave feedback here on the topic if there are problems with it.

The more I think back at this the more I think I was wrong, the world, especially the web is moving towards using "-" as the standard separator, I feel like after we are done with D1 we should adapt to what's more standard by renaming the files and branches accordingly.
