### ISSUE TITLE
Usecases

### ISSUE THREAD

**Issue by anhtuduong** [RadiantIQ/RadiantIQ#2]
[use-cases-diagram](https://app.diagrams.net/#G1zWW2hMF2cmYPT9vErArqi8reYx1_jJmI#%7B%22pageId%22%3A%22CCdd5q1RcuB6t-KJHea2%22%7D)
[use-cases-instructions](https://didatticaonline.unitn.it/dol/pluginfile.php/1816393/mod_resource/content/3/L5_UseCaseDiagram.pdf)
[use-cases-instructions-2](https://didatticaonline.unitn.it/dol/pluginfile.php/1817598/mod_resource/content/1/L7_UC_Specification.pdf)

**Comment by anhtuduong** [comment]
@pertipo The line `\end{document}` should not be at the end of any section file (in this case in usecase.tex). It will end the whole PDF doc without generating Context, Component diagram and so on... I fixed it now

**Comment by pertipo** [comment]
Yeah sorry, I used an external latex document to easily render only this section and keep track of every package needed. I probably copy pasted that last line mistakingly while I was copy pasting the main body of the section.
Thanks for the correction

**Comment by LorenzoCattai** [comment]
Completed for D1.
