### ISSUE TITLE
Definition of Tests

### ISSUE THREAD

**Issue by anhtuduong** [RadiantIQ/RadiantIQ#22]

**Comment by pertipo** [comment]
I just found out that the actual list of tests is also needed for D2. In the description of the requirements for D2 the professor stated "For Deliverable 2, only a definition of tests is to be provided, following the template that will be presented during the lectures.
The code implementation of tests is instead to be included in Deliverable 3." and the template provided is of a textual enumeration of each needed test (see slide 186 of: https://didatticaonline.unitn.it/dol/pluginfile.php/1830034/mod_resource/content/2/Software_Testing.pdf)

**Comment by anhtuduong** [comment]
I will add the table now...
