### ISSUE TITLE
Git Strategy

### ISSUE THREAD

**Issue by anhtuduong** [RadiantIQ/RadiantIQ#23]
[radiantiq-git-strategy.drawio](https://drive.google.com/file/d/1N_1UVGXyQerBSjeZacNdONv9gUi9iZfK/view?usp=drive_link)

**Comment by loreneg** [comment]
I started the task by creating a draft visualization and grouping the branches names types.

**Comment by loreneg** [comment]
the Git strategy is ready,  we uptaded it with a final proposal which we think makes sense, feel free to give any changes suggestion if you'd like
