### ISSUE TITLE
Architecture Description

### ISSUE THREAD

**Issue by anhtuduong** [RadiantIQ/RadiantIQ#24]
[radiantiq-architecture-description.drawio](https://drive.google.com/file/d/1S5pvaFO3iFo1Qi1aAJp3kKiiBF75mFMx/view?usp=drive_link)
How and What to do: [Lab1 - Architecture organization tools.pdf](https://didatticaonline.unitn.it/dol/pluginfile.php/1815511/mod_resource/content/2/Lab1%20-%20Architecture%20organization%20tools.pdf) (from page 5)
This is basically a really free style description of the entire project and inner workings.

**Comment by LorenzoCattai** [comment]
I have made an initial draft with all the things shown in the slides tho it doesn't seem complex enough, it feels very empty, I will ask the professor what else can be added without going over the scope.

**Comment by anhtuduong** [comment]
@LorenzoCattai did you push it? Can I see it?

**Comment by anhtuduong** [comment]
I'm also joining this because I already draw some microservice design diagrams and documentations.

**Comment by anhtuduong** [comment]
Microservice architecture. Description will be updated soon.

![Image](https://github.com/RadiantIQ/RadiantIQ/assets/76017474/47430e7e-91ff-4362-aacb-3304a3472586)
