### ISSUE TITLE
Meeting Log

### ISSUE THREAD

**Issue by anhtuduong** [RadiantIQ/RadiantIQ#29]
*moved to [radiantiq-meeting-log](https://docs.google.com/document/d/1XukGdMQjtuoba_GhpM0Amo2-4O77Gr__NmDPSNTMKvs/edit?usp=sharing)*

**Comment by anhtuduong** [comment]
## Meeting 2/5/24:

Towards D2: focus on the agile management of the project
https://didatticaonline.unitn.it/dol/pluginfile.php/1828441/mod_resource/content/1/SW-eng-L16-Agile-hands-on.pdf
https://didatticaonline.unitn.it/dol/mod/forum/discuss.php?d=313894
Tech stack: https://didatticaonline.unitn.it/dol/mod/forum/discuss.php?d=313726

---

### About D2:

#### 1. Architecture Description
write an email to understand what he wants exactly: Lorenzo

#### 2. Product Backlog (definition of the user stories)
Gabriele will handle
Extension of the user stories but with development activities and their time allocation

#### 3. Definition of tests
Anh Tu will handle
V-model testing

#### 4. Git strategy
Git Flow
present actual branch situation with real branch names as examples
Lorenzo

#### 5. Definition of Done
Anh Tu will start the doc first
Then everyone will put their idea on how to decide “Done” in an activity
Code of Conduct

#### 6. How-to demo
write an email to understand what he wants exactly: Lorenzo

#### 7. SPRINT 1:
Sprint backlog: already defined in github
Sprint Review and Sprint Retrospective: should be concluded at the end of sprint 1
burndown chart: Lorenzo looks for github, if not, Anh Tu will use his thing


ask to sartore luca before writing the email

**Comment by LorenzoCattai** [comment]
We decided that it was inappropriate to keep the `meeting log` here as an Issue, having it as a `Draft item` in the [RadiantIQ project](https://github.com/users/RadiantIQ/projects/1) also doesn't seem ideal but most importantly neither method allows concurrent editing and commenting of the document, for this reason we made a shared Google Document appropriately named [radiantiq-meeting-log](https://docs.google.com/document/d/1XukGdMQjtuoba_GhpM0Amo2-4O77Gr__NmDPSNTMKvs/edit?usp=sharing) that everyone can visualize, it's owned by a dedicated Google Account named `RadiantIQ`.
