### ISSUE TITLE
Initial Environment Setup Ideas and Tests

### ISSUE THREAD

**Issue by anhtuduong** [RadiantIQ/RadiantIQ#31]
Based on #20 , we need to setup the environment for the platform, including:
- Containerize each microservice using Docker and deploy them to a container orchestration platform like Kubernetes. Kubernetes provides features for managing and scaling containers.
- Service Discovery and Load Balancing: Implement service discovery and load balancing mechanisms to enable dynamic service registration and discovery. Tools like Kubernetes Service Discovery or HashiCorp Consul.
- API Gateway: Consider using an API gateway to provide a single entry point for clients to access our microservices. The API gateway can handle authentication, routing, load balancing. Popular choices include Kong and Netflix Zuul.
- Monitoring and Logging: Implement monitoring and logging for each microservice to track performance, errors, and other metrics. Tools like Prometheus and ELK stack (Elasticsearch, Logstash, Kibana) can help
- Security: Ensure that each microservice is secure and follows best practices for authentication, authorization, and data protection. Use technologies like JSON Web Tokens (JWT) for authentication and OAuth 2.0 for authorization.
- Testing and Deployment: Implement automated testing and continuous integration/continuous deployment (CI/CD) pipelines for each microservice.

**Comment by anhtuduong** [comment]
After some research about microservice structure, i propose first to organize the repo as follow:

```
RadiantIQ/
|
├── backend/
|   |
│   ├── <name>-service/       # service template
│   │   ├── api/                # API definition and documentation
│   │   │   └── openapi.yaml    # OpenAPI 3.0 specification
│   │   ├── src/                # Source code
│   │   │   ├── controllers/    # Controllers for handling requests
│   │   │   ├── models/         # Mongoose models for data schema
│   │   │   ├── routes/         # Express.js routes
│   │   │   └── index.js        # Entry point of the service
│   │   ├── .github/            # GitHub Actions workflows
│   │   │   └── workflows/      # CI/CD configuration files
│   │   │       └── ci.yml      # Example: CI workflow
│   │   ├── tests/              # Tests
│   │   ├── documents/          # Documentations
│   │   ├── .gitignore
│   │   ├── Dockerfile          # Dockerfile for containerization
│   │   ├── package.json        # Node.js dependencies
│   │   └── README.md
|   |
│   ├── account-service/   # for example, the account-service is structured like this
│   │   ├── api/
│   │   │   └── openapi.yaml
│   │   ├── src/
│   │   │   ├── controllers/
│   │   │   │   └── accountController.js
│   │   │   ├── models/
│   │   │   │   └── Account.js
│   │   │   ├── routes/
│   │   │   │   └── accountRoutes.js
│   │   │   └── index.js
│   │   ├── .github/
│   │   │   └── workflows/
│   │   │       └── ci.yml
│   │   ├── tests/
│   │   ├── documents/
│   │   ├── .gitignore
│   │   ├── Dockerfile
│   │   ├── package.json
│   │   └── README.md
|   |
│   ├── course-service/         # Same as service template
│   ├── class-service/          # Same as service template
│   ├── article-service/        # Same as service template
│   ├── payment-service/        # Same as service template
│   ├── library-service/        # Same as service template
│   ├── minigame-service/       # Same as service template
│   ├── ranking-service/        # Same as service template
│   └── chat-service/           # Same as service template
|
|── frontend/
│   ├── Dockerfile
│   ├── public/
│   │   └── index.html
│   ├── src/
│   │   ├── components/
│   │   ├── views/
│   │   ├── assets/
│   │   └── App.vue
│   ├── .gitignore
│   ├── package.json
│   └── README.md
│
├── docker-compose.yml
├── .github/
│   └── workflows/
│       └── ci.yml
├── tests/
├── deliverables/
├── documents/
├── .gitignore
└── README.md
```

Where each service is independent from each other and comunicate via API.
I need the agreement from everyone so I can setup the `docker` and `github action` for each service, and also setup Render deployment for the whole webapp.  Note that this is just a structure for the setup, I will not start implementing API or Database... @LorenzoCattai @pertipo @loreneg 

![Image](https://github.com/RadiantIQ/RadiantIQ/assets/76017474/52664a6f-ded2-435e-8624-b8f5d3edd041)

**Comment by anhtuduong** [comment]
For `nodejs` i will choose the latest LTS version `20.23.1` with `npm 10.5.2`

**Comment by LorenzoCattai** [comment]
This looks really good, this is almost exactly what I was thinking of doing as well, the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) scopes would simply use the respective service part, this is going to look quite nice.

Just a few things
- I think we should rename `documents` to just `docs` like most big projects do.
- I was thinking of using `GraphQL` (we can still use `express.js`) for the APIs instead of `RESTful` like originally proposed in the professor's slides, I have talked to him about this and he is onboard. I would do this to spend time learning what companies are moving towards nowadays (for example the new GitHub APIs are only available as `GraphQL` APIs), also it's much more efficent and better overall.
- I was thinking of using `Typescript + Angular + NgBootstrap` for the frontend, the professor is also onboard with this. I would do this for the same reasons as using `GraphQL` mostly.
- While we can use [Render](https://render.com/) as our `PaaS` Idealy I would love to self host a small `PaaS Infrastructure` using one of the many great open source alternatives, I was thinking of having a node in my private server and a few on Oracle free tier arm servers, there is also a lot of free stuff on cloudflare like their CDNs, I have talked to the professor also about this and he is also onboard with this idea. For starting tho we can use [Render](https://render.com/) tho, the switch can be done in a second moment easily after I find the time to setup the `PaaS architecture`.

**Comment by anhtuduong** [comment]
@LorenzoCattai 
- For the naming the documents directory, i agree. If do so, we also need to rename the `root/documents` to `root/docs` as well. We can do that after the D2.
- Ok with `GraphQL`.
- For the frontend, let's make a separate issue on this.
- Render is for deployment of the product, I think most of the time we need to test all the work on self-host machine. For now I already setup Render.

**Comment by anhtuduong** [comment]
@LorenzoCattai I have setup a service called `template-and-test-microservices`, can you go to [this README.md manual](https://github.com/RadiantIQ/RadiantIQ/tree/main/backend/template-and-test-microservices#containerize-the-service) and follow the instruction starting from `Containerize the service` section to check if it works... Thank you!
PS: the setup is in `main` branch now so you don't need to switch.

**Comment by anhtuduong** [comment]
@LorenzoCattai  All the microservices have been deployed on Render successfully! Each service will be deployed on separated Render's port:
- https://radiantiq-test-account-service.onrender.com
- https://radiantiq-test-chat-service.onrender.com
- https://radiantiq-test-class-service.onrender.com
- https://radiantiq-test-course-service.onrender.com
- https://radiantiq-test-library-service.onrender.com
- https://radiantiq-test-minigame-service.onrender.com
- https://radiantiq-test-payment-service.onrender.com
- https://radiantiq-test-ranking-service.onrender.com

This proved that we can use Render for deploying our app. The next thing should be develop API so these microservices can communicate with each other, and also a simple frontend so that the final product will have a single endpoint radiantiq.com.

**Comment by LorenzoCattai** [comment]
Small clarification, we own `radiantiq.org`, not the `.com` version, that was already taken unfortunately.
