### ISSUE TITLE
Actors

### ISSUE THREAD

**Issue by anhtuduong** [RadiantIQ/RadiantIQ#5]
[actors-diagram](https://app.diagrams.net/#G1aPooUkf_XC-CtlAPJUaL80X6rs7UkbPg#%7B%22pageId%22%3A%22Wm-Oz_30ZJCohY5nJ_f-%22%7D)
[actors-instructions](https://didatticaonline.unitn.it/dol/pluginfile.php/1817340/mod_resource/content/1/L6_ProjectDefinition.pdf)

`Student`, `Professor`, `Publisher`, `Developer`, `System Admin`, `Course Supervisor`, `AI Supervisor` and `Tech Support` actors are more specifically **roles** that **provide an additional set of unique functionalities**.
Each `Registered` (User) can have multiple roles assigned to them simultaneously, in a composite role system similar to the one used in Discord. We choose this model to easily separate functionalities and assign them to users modularly.

**Comment by LorenzoCattai** [comment]
Completed for D1.
