### ISSUE TITLE
Functional Requirements

### ISSUE THREAD

**Issue by anhtuduong** [RadiantIQ/RadiantIQ#6]
[functional-requirements-instructions](https://didatticaonline.unitn.it/dol/pluginfile.php/1817598/mod_resource/content/1/L7_UC_Specification.pdf)
[functional-requirements-instructions-2](https://didatticaonline.unitn.it/dol/pluginfile.php/1815499/mod_resource/content/2/SW-eng-lecture-5-requirement-eng.pdf)

**Comment by LorenzoCattai** [comment]
Completed for D1.
