### ISSUE TITLE
Context Diagram

### ISSUE THREAD

**Issue by anhtuduong** [RadiantIQ/RadiantIQ#8]
[context-diagram](https://drive.google.com/file/d/1awPwyqmXyzE1cD7Ok_Z-ExufG_n7J4hH/)
[context-diagram-instructions](https://didatticaonline.unitn.it/dol/pluginfile.php/1818371/mod_resource/content/1/L8_ContextDiagram.pdf)

**Comment by anhtuduong** [comment]
@pertipo I just checkout your [branch](https://github.com/RadiantIQ/RadiantIQ/tree/docs/8_context_diagram) and there was an error when generating pdf: "location for context component png not found". This is also related to the code in Makefile, we have specified `$(wildcard images/*) ` which means we should have a folder images inside D1. (Probably because of my wrong suggestion yesterday). Anyway I fixed it and pushed to the same branch.

**Comment by pertipo** [comment]
Ok, thanks. We also need to fix this in a couple more branches then. As I used images there too

**Comment by anhtuduong** [comment]
I will handle this

**Comment by LorenzoCattai** [comment]
Completed for D1.
