### ISSUE TITLE
Component Diagram

### ISSUE THREAD

**Issue by anhtuduong** [RadiantIQ/RadiantIQ#9]
[component-diagram](https://drive.google.com/file/d/1ImHHjy2mM1YRPLGSzZB45YXTDeAv39LA/view?usp=sharing)
[component-diagram-instructions](https://didatticaonline.unitn.it/dol/pluginfile.php/1819271/mod_resource/content/1/L9-SA%20and%20Components%20Diagrams.pdf)

**Comment by LorenzoCattai** [comment]
Completed for D1.
